### ISSUE TITLE
Issues with VIRecorder.js

### ISSUE THREAD

**Issue by ghost** [imalhasaranga/VideoRecorderJs#1]
I downloaded this project as a zip in github. However, upon running this on the latest version of Chrome (36) I got the following error when ever the recording stops

20.173520490936024 Time : 14.177 Frames : 286 VIRecorder.js:222
Uncaught TypeError: Cannot read property 'clear' of undefined VIRecorder.js:157
init.stopCapture VIRecorder.js:157
startCountDown index.html:150
(anonymous function)

I have not edited any of this code

**Comment by ghost** [comment]
Extra Info: Line 157 of VIRecorder.js is "recorder.clear();" this gives the error of "Uncaught TypeError: Cannot read property 'clear' of undefined

**Comment by imalhasaranga** [comment]
Hi,
I tested again but I don't find the error you are mentioning, but however I think this error might have come because recorder.clear()  is called before wav was generated.  so I did a small update please update. 

You might get 

Cannot read property 'width' of undefined  in whammy.js:184 in rare occasions, but it does not affect

**Comment by mmahnken** [comment]
I'm getting this error as well. Any updates?

**Comment by imalhasaranga** [comment]
Hi, 
This version only support chrome latest and opera only, which browser you were testing

-----Original Message-----

**Comment by imalhasaranga** [comment]
VIRecorder has been risen from the ashes :) I have released the version 1.0.0 which has this bug fix also have added multiple browser support with MediaStreamRecorder specification
